apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-k8s-dashboard-own
  name: app-k8s-dashboard-own
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-k8s-dashboard-own
  strategy: {}
  template:
    metadata:
      labels:
        app: app-k8s-dashboard-own
    spec:
      containers:
      - image: ghcr.io/wiktorvip/app-k8s-dashboard-own:1.0
        name: app-k8s-dashboard-own
        ports:
          - containerPort: 9040

